---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: company-app-prod
--- 
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: company-app-prod
    namespace: company-app-prod
  spec:
    replicas: 4
    strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
    selector:
      matchLabels:
        app: company-app-prod
    template:
      metadata:
        labels:
          app: company-app-prod
      spec:
        containers:
          - name: company-app-prod
            image: localhost:5000/company_app_img:v1
            imagePullPolicy: Always
            resources:
              limits:
                cpu: "0.25"
                memory: "512Mi"
              requests:
                cpu: "250m"
                memory: "50Mi"

---
  kind: Service
  apiVersion: v1
  metadata:
    name: company-app-prod
    namespace: company-app-prod
  spec:
    selector:
      app: company-app-prod
    ports:
      - name: http
        port: 8101
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
      